version: '3.7'

services:
  mysql:
    image: mysql
    container_name: mysql57
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_DATABASE: 'algalog'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
